---
# Source: cf-app/templates/app.yaml
apiVersion: v1
kind: Service
metadata:
  name: cloud-sample-node-chat-demo-app
  namespace: docker
spec:
  selector:
    app: cloud-sample-node-chat-demo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8089

---
# Source: cf-app/templates/app.yaml
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: cloud-sample-node-chat-demo-app
  namespace: docker
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: cloud-sample-node-chat-demo-app
    port: 8080
    host: cloud-sample-node-chat-docker.demo-jan.istio.shoot.canary.k8s-hana.ondemand.com
  rules:
    - path: /.*
      methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - HEAD
      accessStrategies:
        - handler: allow

---
# Source: cf-app/templates/app.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloud-sample-node-chat-demo-app
spec:
  podSelector:
    matchLabels:
      release: demo-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: istio-system
      podSelector:
        matchLabels:
          app: istio-ingressgateway